# version: 2
# updates:
#   - package-ecosystem: "npm"
#     directory: "/random-data-service"
#     schedule:
#       interval: "daily"
#     ignore:
#       - dependency-name: "chance"
#       - dependency-name: "express"
#   - package-ecosystem: "npm"
#     directory: "/data-changer-service"
#     schedule:
#       interval: "daily"
#     ignore:
#       - dependency-name: "fastify"
#       - dependency-name: "kafkajs"
#   - package-ecosystem: "npm"
#     directory: "/data-filter-service"
#     schedule:
#       interval: "daily"
#     ignore:
#       - dependency-name: "pg"
#       - dependency-name: "kafkajs"
#       - dependency-name: "socket.io"
#       - dependency-name: "socket.io-client"
#   - package-ecosystem: "npm"
#     directory: "/display-data-service"
#     schedule:
#       interval: "daily"
#     ignore:
#       - dependency-name: "pg"
#       - dependency-name: "@hapi/hapi"
#       - dependency-name: "socket.io"
#   - package-ecosystem: "npm"
#     directory: "/random-data-service"
#     schedule:
#       interval: "daily"
#     target-branch: "console_exporter"
#     ignore:
#       - dependency-name: "chance"
#       - dependency-name: "express"
#   - package-ecosystem: "npm"
#     directory: "/data-changer-service"
#     schedule:
#       interval: "daily"
#     target-branch: "console_exporter"
#     ignore:
#       - dependency-name: "fastify"
#       - dependency-name: "kafkajs"
#   - package-ecosystem: "npm"
#     directory: "/data-filter-service"
#     schedule:
#       interval: "daily"
#     target-branch: "console_exporter"
#     ignore:
#       - dependency-name: "pg"
#       - dependency-name: "kafkajs"
#       - dependency-name: "socket.io"
#       - dependency-name: "socket.io-client" 
#   - package-ecosystem: "npm"
#     directory: "/display-data-service"
#     schedule:
#       interval: "daily"
#     target-branch: "console_exporter"
#     ignore:
#       - dependency-name: "pg"
#       - dependency-name: "@hapi/hapi"
#       - dependency-name: "socket.io"
#   - package-ecosystem: "npm"
#     directory: "/random-data-service"
#     schedule:
#       interval: "daily"
#     target-branch: "otelcol_exporter"
#     ignore:
#       - dependency-name: "chance"
#       - dependency-name: "express"
#   - package-ecosystem: "npm"
#     directory: "/data-changer-service"
#     schedule:
#       interval: "daily"
#     target-branch: "otelcol_exporter"
#     ignore:
#       - dependency-name: "fastify"
#       - dependency-name: "kafkajs"
#   - package-ecosystem: "npm"
#     directory: "/data-filter-service"
#     schedule:
#       interval: "daily"
#     target-branch: "otelcol_exporter"
#     ignore:
#       - dependency-name: "pg"
#       - dependency-name: "kafkajs"
#       - dependency-name: "socket.io"
#       - dependency-name: "socket.io-client"  
#   - package-ecosystem: "npm"
#     directory: "/display-data-service"
#     schedule:
#       interval: "daily"
#     target-branch: "otelcol_exporter"
#     ignore:
#       - dependency-name: "pg"
#       - dependency-name: "@hapi/hapi"
#       - dependency-name: "socket.io"
