version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/random-data-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/data-changer-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/data-filter-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/display-data-service"
    schedule:
      interval: "daily"
