version: '3'

networks:
  default:
    name: hyperfoil-test
    driver: bridge

services:
  # Thanks to https://github.com/scholzj/strimzi-compose-up for the - Kafka - part.
  zookeeper:
    image: quay.io/strimzi/kafka:0.32.0-kafka-3.3.1
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
      ]
    ports:
    - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: quay.io/strimzi/kafka:0.32.0-kafka-3.2.1
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    hostname: kafka
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  postgres:
    hostname: postgres
    image: postgres:10.5
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  random-data-service:
    build:
      context: ./random-data-service
      dockerfile: Dockerfile
    hostname: rds
    ports:
      - "8080:8080"

  data-changer-service:
    build:
      context: ./data-changer-service
      dockerfile: Dockerfile
    hostname: dcs
    ports:
      - "8081:8081"

  data-filter-service:
    build:
      context: ./data-filter-service
      dockerfile: Dockerfile
    hostname: dfs
    ports:
      - "8082:8082"
    depends_on: [postgres]

  display-data-service:
    build:
      context: ./display-data-service
      dockerfile: Dockerfile
    hostname: dds
    ports:
      - "8083:8083"
    depends_on: [postgres]  